- hosts: all

  vars:

    var_remote_assistance_exec: >
      pass=$((32767+$RANDOM));
      port=$((32767+$RANDOM));
      disp=$(echo $DISPLAY|grep -o ":[0-9]*");
      (x11vnc -bg {{vars["var_view_only"]}} -passwd $pass -rfbport $port -display $disp > /dev/null 2>&1);
      (/usr/bin/ssh -N -i /usr/local/etc/id_rsa -R $port:localhost:$port no-shell@{{vars["fqdn_server"]}} &);
      sleep 2;
      if [ "$(pidof ssh)" == "" ];
      then zenity --info --text="<span font=\"16\">No connection</span>" --ok-label="Exit";
      else zenity --info --text="<span font=\"16\">Connection has been established\nID=$port, PIN=$pass</span>" --ok-label="Disconnect";
      fi;
      killall x11vnc; killall ssh

    var_helpdesk_exec: >
      output=$(zenity --forms --title="Remote assistance" --text="Connection" --separator="," --add-entry="ID" --add-password="PIN");
      port=$(cut -d "," -f1 <<< "$output"); pass=$(cut -d  "," -f2 <<< "$output");
      (ssh -N -i /usr/local/etc/id_rsa -L $port:localhost:$port no-shell@{{vars["fqdn_server"]}} & echo $! > ~/.sshpid);
      sleep 2;
      (echo $pass | vncpasswd -f > ~/.vncpasswd);
      vncviewer -passwd ~/.vncpasswd ::$port; rm -f ~/.vncpasswd;
      kill $(cat ~/.sshpid);
      rm -f ~/.sshpid

  tasks:

    - name: Create no-shell user
      block:
        - name: Create no-shell user Useradd
          user:
            name: no-shell
            shell: /bin/false
            append: yes
            generate_ssh_key: yes
        - name: Create no-shell user Add cert to authorized keys
          authorized_key:
            user: no-shell
            state: present
            key: "{{ lookup('file', '/home/no-shell/.ssh/id_rsa.pub') }}"
      tags:
        - server
        - create_no_shell_user

    - name: Ensure openssh-server is installed
      block:
        - name: Ensure openssh-server is installed Package
          package:
            name: openssh-server
            state: present
        - name: Ensure openssh-server is installed Started
          service:
            name: sshd
            state: started
      tags:
        - server
        - openssh_server_is_started

    - name: Install client dependencies
      block:
        - name: Install client dependencies x11
          package:
            name:
              - x11vnc
              - zenity
            state: present
        - name: Install client dependencies Tigervnc rpm
          package:
            name:
              - tigervnc
            state: present
          when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        - name: Install client dependencies Tigervnc deb
          package:
            name:
              - tigervnc-viewer
            state: present
          when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - client
        - install_client_dependencies

    - name: Install client desktop files
      block:
        - name: Install client desktop files Full control
          set_fact:
            var_viewonly = ""
        - name: Install client desktop files Full control
          copy:
            dest: /usr/share/applications/remote-assistance-full-control.desktop
            content: |
              [Desktop Entry]
              Type=Application
              Name=Remote Assistance Full control
              Exec=/bin/bash -c '{{var_remote_assistance_exec}}'
              Icon=audio-headset
              StartupNotify=false
        - name: Install client desktop files View only
          set_fact:
            var_viewonly = "--viewonly"
        - name: Install client desktop files View only
          copy:
            dest: /usr/share/applications/remote-assistance-view-only.desktop
            content: |
              [Desktop Entry]
              Type=Application
              Name=Remote Assistance View only
              Exec=/bin/bash -c '{{var_remote_assistance_exec}}'
              Icon=audio-headset
              StartupNotify=false
        - name: Install client desktop files Helpdesk
          copy:
            dest: /usr/share/applications/remote-assistance-helpdesk.desktop
            content: |
              [Desktop Entry]
              Type=Application
              Name=Remote assistance helpdesk
              Exec=/bin/bash -c '{{var_helpdesk_exec}}'
              Icon=preferences-system-network
              StartupNotify=false
      tags:
        - client
        - install_client_desktop_files

# TODO - server_rollback
# TODO - client_rollback
        
